- name: Frontend Playbook
  hosts: all
  become: true
  tasks:
    - name: Installing Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
    - name: copy expense file
      ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

    - name: Recursively remove directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory


    - name: Download file content and extract
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
        dest: /tmp/frontend.zip
        remote_src: yes

    - name: Start Nginx Service
      ansible.builtin.systemd_service:
        state: restarted
        name: Nginx
        enabled: true


